using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace PullRequest_Service.Migrations
{
    /// <inheritdoc />
    public partial class SecondMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Teams",
                columns: table => new
                {
                    TeamName = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    TeamId = table.Column<int>(type: "integer", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "NOW()")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Teams", x => x.TeamName);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Username = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    TeamName = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.UserId);
                    table.ForeignKey(
                        name: "FK_Users_Teams_TeamName",
                        column: x => x.TeamName,
                        principalTable: "Teams",
                        principalColumn: "TeamName",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateTable(
                name: "PullRequests",
                columns: table => new
                {
                    PullRequestId = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    PullRequestName = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    AuthorId = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    MergedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PullRequests", x => x.PullRequestId);
                    table.ForeignKey(
                        name: "FK_PullRequests_Users_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Users",
                        principalColumn: "UserId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "PullRequestReviewers",
                columns: table => new
                {
                    PullRequestId = table.Column<string>(type: "character varying(100)", nullable: false),
                    ReviewerId = table.Column<string>(type: "character varying(100)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PullRequestReviewers", x => new { x.PullRequestId, x.ReviewerId });
                    table.ForeignKey(
                        name: "FK_PullRequestReviewers_PullRequests_PullRequestId",
                        column: x => x.PullRequestId,
                        principalTable: "PullRequests",
                        principalColumn: "PullRequestId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PullRequestReviewers_Users_ReviewerId",
                        column: x => x.ReviewerId,
                        principalTable: "Users",
                        principalColumn: "UserId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Teams",
                columns: new[] { "TeamName", "CreatedAt", "TeamId" },
                values: new object[,]
                {
                    { "Analytics", new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "API", new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Auth", new DateTime(2023, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Backend", new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Core", new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Data Science", new DateTime(2023, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "DevOps", new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Frontend", new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Infrastructure", new DateTime(2023, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Integration", new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "ML", new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Mobile", new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Notifications", new DateTime(2023, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Payments", new DateTime(2023, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Platform", new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "QA", new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Recommendations", new DateTime(2023, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Search", new DateTime(2023, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "Security", new DateTime(2023, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc), 0 },
                    { "UI-UX", new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc), 0 }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "UserId", "IsActive", "TeamName", "Username" },
                values: new object[,]
                {
                    { "user-1", true, "Backend", "BackendUser1" },
                    { "user-10", false, "Backend", "BackendUser10" },
                    { "user-100", false, "Platform", "PlatformUser10" },
                    { "user-101", true, "Payments", "PaymentsUser1" },
                    { "user-102", true, "Payments", "PaymentsUser2" },
                    { "user-103", true, "Payments", "PaymentsUser3" },
                    { "user-104", true, "Payments", "PaymentsUser4" },
                    { "user-105", true, "Payments", "PaymentsUser5" },
                    { "user-106", true, "Payments", "PaymentsUser6" },
                    { "user-107", true, "Payments", "PaymentsUser7" },
                    { "user-108", true, "Payments", "PaymentsUser8" },
                    { "user-109", true, "Payments", "PaymentsUser9" },
                    { "user-11", true, "Frontend", "FrontendUser1" },
                    { "user-110", false, "Payments", "PaymentsUser10" },
                    { "user-111", true, "Auth", "AuthUser1" },
                    { "user-112", true, "Auth", "AuthUser2" },
                    { "user-113", true, "Auth", "AuthUser3" },
                    { "user-114", true, "Auth", "AuthUser4" },
                    { "user-115", true, "Auth", "AuthUser5" },
                    { "user-116", true, "Auth", "AuthUser6" },
                    { "user-117", true, "Auth", "AuthUser7" },
                    { "user-118", true, "Auth", "AuthUser8" },
                    { "user-119", true, "Auth", "AuthUser9" },
                    { "user-12", true, "Frontend", "FrontendUser2" },
                    { "user-120", false, "Auth", "AuthUser10" },
                    { "user-121", true, "Notifications", "NotificationsUser1" },
                    { "user-122", true, "Notifications", "NotificationsUser2" },
                    { "user-123", true, "Notifications", "NotificationsUser3" },
                    { "user-124", true, "Notifications", "NotificationsUser4" },
                    { "user-125", true, "Notifications", "NotificationsUser5" },
                    { "user-126", true, "Notifications", "NotificationsUser6" },
                    { "user-127", true, "Notifications", "NotificationsUser7" },
                    { "user-128", true, "Notifications", "NotificationsUser8" },
                    { "user-129", true, "Notifications", "NotificationsUser9" },
                    { "user-13", true, "Frontend", "FrontendUser3" },
                    { "user-130", false, "Notifications", "NotificationsUser10" },
                    { "user-131", true, "Search", "SearchUser1" },
                    { "user-132", true, "Search", "SearchUser2" },
                    { "user-133", true, "Search", "SearchUser3" },
                    { "user-134", true, "Search", "SearchUser4" },
                    { "user-135", true, "Search", "SearchUser5" },
                    { "user-136", true, "Search", "SearchUser6" },
                    { "user-137", true, "Search", "SearchUser7" },
                    { "user-138", true, "Search", "SearchUser8" },
                    { "user-139", true, "Search", "SearchUser9" },
                    { "user-14", true, "Frontend", "FrontendUser4" },
                    { "user-140", false, "Search", "SearchUser10" },
                    { "user-141", true, "Recommendations", "RecommendationsUser1" },
                    { "user-142", true, "Recommendations", "RecommendationsUser2" },
                    { "user-143", true, "Recommendations", "RecommendationsUser3" },
                    { "user-144", true, "Recommendations", "RecommendationsUser4" },
                    { "user-145", true, "Recommendations", "RecommendationsUser5" },
                    { "user-146", true, "Recommendations", "RecommendationsUser6" },
                    { "user-147", true, "Recommendations", "RecommendationsUser7" },
                    { "user-148", true, "Recommendations", "RecommendationsUser8" },
                    { "user-149", true, "Recommendations", "RecommendationsUser9" },
                    { "user-15", true, "Frontend", "FrontendUser5" },
                    { "user-150", false, "Recommendations", "RecommendationsUser10" },
                    { "user-151", true, "Core", "CoreUser1" },
                    { "user-152", true, "Core", "CoreUser2" },
                    { "user-153", true, "Core", "CoreUser3" },
                    { "user-154", true, "Core", "CoreUser4" },
                    { "user-155", true, "Core", "CoreUser5" },
                    { "user-156", true, "Core", "CoreUser6" },
                    { "user-157", true, "Core", "CoreUser7" },
                    { "user-158", true, "Core", "CoreUser8" },
                    { "user-159", true, "Core", "CoreUser9" },
                    { "user-16", true, "Frontend", "FrontendUser6" },
                    { "user-160", false, "Core", "CoreUser10" },
                    { "user-161", true, "API", "APIUser1" },
                    { "user-162", true, "API", "APIUser2" },
                    { "user-163", true, "API", "APIUser3" },
                    { "user-164", true, "API", "APIUser4" },
                    { "user-165", true, "API", "APIUser5" },
                    { "user-166", true, "API", "APIUser6" },
                    { "user-167", true, "API", "APIUser7" },
                    { "user-168", true, "API", "APIUser8" },
                    { "user-169", true, "API", "APIUser9" },
                    { "user-17", true, "Frontend", "FrontendUser7" },
                    { "user-170", false, "API", "APIUser10" },
                    { "user-171", true, "UI-UX", "UIUXUser1" },
                    { "user-172", true, "UI-UX", "UIUXUser2" },
                    { "user-173", true, "UI-UX", "UIUXUser3" },
                    { "user-174", true, "UI-UX", "UIUXUser4" },
                    { "user-175", true, "UI-UX", "UIUXUser5" },
                    { "user-176", true, "UI-UX", "UIUXUser6" },
                    { "user-177", true, "UI-UX", "UIUXUser7" },
                    { "user-178", true, "UI-UX", "UIUXUser8" },
                    { "user-179", true, "UI-UX", "UIUXUser9" },
                    { "user-18", true, "Frontend", "FrontendUser8" },
                    { "user-180", false, "UI-UX", "UIUXUser10" },
                    { "user-181", true, "ML", "MLUser1" },
                    { "user-182", true, "ML", "MLUser2" },
                    { "user-183", true, "ML", "MLUser3" },
                    { "user-184", true, "ML", "MLUser4" },
                    { "user-185", true, "ML", "MLUser5" },
                    { "user-186", true, "ML", "MLUser6" },
                    { "user-187", true, "ML", "MLUser7" },
                    { "user-188", true, "ML", "MLUser8" },
                    { "user-189", true, "ML", "MLUser9" },
                    { "user-19", true, "Frontend", "FrontendUser9" },
                    { "user-190", false, "ML", "MLUser10" },
                    { "user-191", true, "Integration", "IntegrationUser1" },
                    { "user-192", true, "Integration", "IntegrationUser2" },
                    { "user-193", true, "Integration", "IntegrationUser3" },
                    { "user-194", true, "Integration", "IntegrationUser4" },
                    { "user-195", true, "Integration", "IntegrationUser5" },
                    { "user-196", true, "Integration", "IntegrationUser6" },
                    { "user-197", true, "Integration", "IntegrationUser7" },
                    { "user-198", true, "Integration", "IntegrationUser8" },
                    { "user-199", true, "Integration", "IntegrationUser9" },
                    { "user-2", true, "Backend", "BackendUser2" },
                    { "user-20", false, "Frontend", "FrontendUser10" },
                    { "user-200", false, "Integration", "IntegrationUser10" },
                    { "user-21", true, "DevOps", "DevOpsUser1" },
                    { "user-22", true, "DevOps", "DevOpsUser2" },
                    { "user-23", true, "DevOps", "DevOpsUser3" },
                    { "user-24", true, "DevOps", "DevOpsUser4" },
                    { "user-25", true, "DevOps", "DevOpsUser5" },
                    { "user-26", true, "DevOps", "DevOpsUser6" },
                    { "user-27", true, "DevOps", "DevOpsUser7" },
                    { "user-28", true, "DevOps", "DevOpsUser8" },
                    { "user-29", true, "DevOps", "DevOpsUser9" },
                    { "user-3", true, "Backend", "BackendUser3" },
                    { "user-30", false, "DevOps", "DevOpsUser10" },
                    { "user-31", true, "QA", "QAUser1" },
                    { "user-32", true, "QA", "QAUser2" },
                    { "user-33", true, "QA", "QAUser3" },
                    { "user-34", true, "QA", "QAUser4" },
                    { "user-35", true, "QA", "QAUser5" },
                    { "user-36", true, "QA", "QAUser6" },
                    { "user-37", true, "QA", "QAUser7" },
                    { "user-38", true, "QA", "QAUser8" },
                    { "user-39", true, "QA", "QAUser9" },
                    { "user-4", true, "Backend", "BackendUser4" },
                    { "user-40", false, "QA", "QAUser10" },
                    { "user-41", true, "Mobile", "MobileUser1" },
                    { "user-42", true, "Mobile", "MobileUser2" },
                    { "user-43", true, "Mobile", "MobileUser3" },
                    { "user-44", true, "Mobile", "MobileUser4" },
                    { "user-45", true, "Mobile", "MobileUser5" },
                    { "user-46", true, "Mobile", "MobileUser6" },
                    { "user-47", true, "Mobile", "MobileUser7" },
                    { "user-48", true, "Mobile", "MobileUser8" },
                    { "user-49", true, "Mobile", "MobileUser9" },
                    { "user-5", true, "Backend", "BackendUser5" },
                    { "user-50", false, "Mobile", "MobileUser10" },
                    { "user-51", true, "Data Science", "DataScienceUser1" },
                    { "user-52", true, "Data Science", "DataScienceUser2" },
                    { "user-53", true, "Data Science", "DataScienceUser3" },
                    { "user-54", true, "Data Science", "DataScienceUser4" },
                    { "user-55", true, "Data Science", "DataScienceUser5" },
                    { "user-56", true, "Data Science", "DataScienceUser6" },
                    { "user-57", true, "Data Science", "DataScienceUser7" },
                    { "user-58", true, "Data Science", "DataScienceUser8" },
                    { "user-59", true, "Data Science", "DataScienceUser9" },
                    { "user-6", true, "Backend", "BackendUser6" },
                    { "user-60", false, "Data Science", "DataScienceUser10" },
                    { "user-61", true, "Security", "SecurityUser1" },
                    { "user-62", true, "Security", "SecurityUser2" },
                    { "user-63", true, "Security", "SecurityUser3" },
                    { "user-64", true, "Security", "SecurityUser4" },
                    { "user-65", true, "Security", "SecurityUser5" },
                    { "user-66", true, "Security", "SecurityUser6" },
                    { "user-67", true, "Security", "SecurityUser7" },
                    { "user-68", true, "Security", "SecurityUser8" },
                    { "user-69", true, "Security", "SecurityUser9" },
                    { "user-7", true, "Backend", "BackendUser7" },
                    { "user-70", false, "Security", "SecurityUser10" },
                    { "user-71", true, "Infrastructure", "InfrastructureUser1" },
                    { "user-72", true, "Infrastructure", "InfrastructureUser2" },
                    { "user-73", true, "Infrastructure", "InfrastructureUser3" },
                    { "user-74", true, "Infrastructure", "InfrastructureUser4" },
                    { "user-75", true, "Infrastructure", "InfrastructureUser5" },
                    { "user-76", true, "Infrastructure", "InfrastructureUser6" },
                    { "user-77", true, "Infrastructure", "InfrastructureUser7" },
                    { "user-78", true, "Infrastructure", "InfrastructureUser8" },
                    { "user-79", true, "Infrastructure", "InfrastructureUser9" },
                    { "user-8", true, "Backend", "BackendUser8" },
                    { "user-80", false, "Infrastructure", "InfrastructureUser10" },
                    { "user-81", true, "Analytics", "AnalyticsUser1" },
                    { "user-82", true, "Analytics", "AnalyticsUser2" },
                    { "user-83", true, "Analytics", "AnalyticsUser3" },
                    { "user-84", true, "Analytics", "AnalyticsUser4" },
                    { "user-85", true, "Analytics", "AnalyticsUser5" },
                    { "user-86", true, "Analytics", "AnalyticsUser6" },
                    { "user-87", true, "Analytics", "AnalyticsUser7" },
                    { "user-88", true, "Analytics", "AnalyticsUser8" },
                    { "user-89", true, "Analytics", "AnalyticsUser9" },
                    { "user-9", true, "Backend", "BackendUser9" },
                    { "user-90", false, "Analytics", "AnalyticsUser10" },
                    { "user-91", true, "Platform", "PlatformUser1" },
                    { "user-92", true, "Platform", "PlatformUser2" },
                    { "user-93", true, "Platform", "PlatformUser3" },
                    { "user-94", true, "Platform", "PlatformUser4" },
                    { "user-95", true, "Platform", "PlatformUser5" },
                    { "user-96", true, "Platform", "PlatformUser6" },
                    { "user-97", true, "Platform", "PlatformUser7" },
                    { "user-98", true, "Platform", "PlatformUser8" },
                    { "user-99", true, "Platform", "PlatformUser9" }
                });

            migrationBuilder.InsertData(
                table: "PullRequests",
                columns: new[] { "PullRequestId", "AuthorId", "CreatedAt", "MergedAt", "PullRequestName", "Status" },
                values: new object[,]
                {
                    { "pr-1", "user-2", new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #1", "OPEN" },
                    { "pr-10", "user-12", new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #10", "OPEN" },
                    { "pr-100", "user-112", new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #100", "OPEN" },
                    { "pr-11", "user-13", new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #11", "OPEN" },
                    { "pr-12", "user-14", new DateTime(2023, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 14, 13, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #12", "MERGED" },
                    { "pr-13", "user-15", new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #13", "OPEN" },
                    { "pr-14", "user-16", new DateTime(2023, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #14", "OPEN" },
                    { "pr-15", "user-17", new DateTime(2023, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 17, 16, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #15", "MERGED" },
                    { "pr-16", "user-18", new DateTime(2023, 12, 18, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #16", "OPEN" },
                    { "pr-17", "user-19", new DateTime(2023, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #17", "OPEN" },
                    { "pr-18", "user-21", new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 20, 19, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #18", "MERGED" },
                    { "pr-19", "user-22", new DateTime(2023, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #19", "OPEN" },
                    { "pr-2", "user-3", new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #2", "OPEN" },
                    { "pr-20", "user-23", new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #20", "OPEN" },
                    { "pr-21", "user-24", new DateTime(2023, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 23, 22, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #21", "MERGED" },
                    { "pr-22", "user-25", new DateTime(2023, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #22", "OPEN" },
                    { "pr-23", "user-26", new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #23", "OPEN" },
                    { "pr-24", "user-27", new DateTime(2023, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 26, 1, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #24", "MERGED" },
                    { "pr-25", "user-28", new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #25", "OPEN" },
                    { "pr-26", "user-29", new DateTime(2023, 12, 28, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #26", "OPEN" },
                    { "pr-27", "user-31", new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 29, 4, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #27", "MERGED" },
                    { "pr-28", "user-32", new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #28", "OPEN" },
                    { "pr-29", "user-33", new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #29", "OPEN" },
                    { "pr-3", "user-4", new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 5, 4, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #3", "MERGED" },
                    { "pr-30", "user-34", new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 2, 7, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #30", "MERGED" },
                    { "pr-31", "user-35", new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #31", "OPEN" },
                    { "pr-32", "user-36", new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #32", "OPEN" },
                    { "pr-33", "user-37", new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 5, 10, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #33", "MERGED" },
                    { "pr-34", "user-38", new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #34", "OPEN" },
                    { "pr-35", "user-39", new DateTime(2023, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #35", "OPEN" },
                    { "pr-36", "user-41", new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 8, 13, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #36", "MERGED" },
                    { "pr-37", "user-42", new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #37", "OPEN" },
                    { "pr-38", "user-43", new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #38", "OPEN" },
                    { "pr-39", "user-44", new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 11, 16, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #39", "MERGED" },
                    { "pr-4", "user-5", new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #4", "OPEN" },
                    { "pr-40", "user-45", new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #40", "OPEN" },
                    { "pr-41", "user-46", new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #41", "OPEN" },
                    { "pr-42", "user-47", new DateTime(2023, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 14, 19, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #42", "MERGED" },
                    { "pr-43", "user-48", new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #43", "OPEN" },
                    { "pr-44", "user-49", new DateTime(2023, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #44", "OPEN" },
                    { "pr-45", "user-51", new DateTime(2023, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 17, 22, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #45", "MERGED" },
                    { "pr-46", "user-52", new DateTime(2023, 12, 18, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #46", "OPEN" },
                    { "pr-47", "user-53", new DateTime(2023, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #47", "OPEN" },
                    { "pr-48", "user-54", new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 20, 1, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #48", "MERGED" },
                    { "pr-49", "user-55", new DateTime(2023, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #49", "OPEN" },
                    { "pr-5", "user-6", new DateTime(2023, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #5", "OPEN" },
                    { "pr-50", "user-56", new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #50", "OPEN" },
                    { "pr-51", "user-57", new DateTime(2023, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 23, 4, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #51", "MERGED" },
                    { "pr-52", "user-58", new DateTime(2023, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #52", "OPEN" },
                    { "pr-53", "user-59", new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #53", "OPEN" },
                    { "pr-54", "user-61", new DateTime(2023, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 26, 7, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #54", "MERGED" },
                    { "pr-55", "user-62", new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #55", "OPEN" },
                    { "pr-56", "user-63", new DateTime(2023, 12, 28, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #56", "OPEN" },
                    { "pr-57", "user-64", new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 29, 10, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #57", "MERGED" },
                    { "pr-58", "user-65", new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #58", "OPEN" },
                    { "pr-59", "user-66", new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #59", "OPEN" },
                    { "pr-6", "user-7", new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 8, 7, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #6", "MERGED" },
                    { "pr-60", "user-67", new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 2, 13, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #60", "MERGED" },
                    { "pr-61", "user-68", new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #61", "OPEN" },
                    { "pr-62", "user-69", new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #62", "OPEN" },
                    { "pr-63", "user-71", new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 5, 16, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #63", "MERGED" },
                    { "pr-64", "user-72", new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #64", "OPEN" },
                    { "pr-65", "user-73", new DateTime(2023, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #65", "OPEN" },
                    { "pr-66", "user-74", new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 8, 19, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #66", "MERGED" },
                    { "pr-67", "user-75", new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #67", "OPEN" },
                    { "pr-68", "user-76", new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #68", "OPEN" },
                    { "pr-69", "user-77", new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 11, 22, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #69", "MERGED" },
                    { "pr-7", "user-8", new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #7", "OPEN" },
                    { "pr-70", "user-78", new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #70", "OPEN" },
                    { "pr-71", "user-79", new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #71", "OPEN" },
                    { "pr-72", "user-81", new DateTime(2023, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 14, 1, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #72", "MERGED" },
                    { "pr-73", "user-82", new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #73", "OPEN" },
                    { "pr-74", "user-83", new DateTime(2023, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #74", "OPEN" },
                    { "pr-75", "user-84", new DateTime(2023, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 17, 4, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #75", "MERGED" },
                    { "pr-76", "user-85", new DateTime(2023, 12, 18, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #76", "OPEN" },
                    { "pr-77", "user-86", new DateTime(2023, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #77", "OPEN" },
                    { "pr-78", "user-87", new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 20, 7, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #78", "MERGED" },
                    { "pr-79", "user-88", new DateTime(2023, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #79", "OPEN" },
                    { "pr-8", "user-9", new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #8", "OPEN" },
                    { "pr-80", "user-89", new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #80", "OPEN" },
                    { "pr-81", "user-91", new DateTime(2023, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 23, 10, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #81", "MERGED" },
                    { "pr-82", "user-92", new DateTime(2023, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #82", "OPEN" },
                    { "pr-83", "user-93", new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #83", "OPEN" },
                    { "pr-84", "user-94", new DateTime(2023, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 26, 13, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #84", "MERGED" },
                    { "pr-85", "user-95", new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #85", "OPEN" },
                    { "pr-86", "user-96", new DateTime(2023, 12, 28, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #86", "OPEN" },
                    { "pr-87", "user-97", new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 29, 16, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #87", "MERGED" },
                    { "pr-88", "user-98", new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #88", "OPEN" },
                    { "pr-89", "user-99", new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #89", "OPEN" },
                    { "pr-9", "user-11", new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 11, 10, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #9", "MERGED" },
                    { "pr-90", "user-101", new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 2, 19, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #90", "MERGED" },
                    { "pr-91", "user-102", new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #91", "OPEN" },
                    { "pr-92", "user-103", new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #92", "OPEN" },
                    { "pr-93", "user-104", new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 5, 22, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #93", "MERGED" },
                    { "pr-94", "user-105", new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #94", "OPEN" },
                    { "pr-95", "user-106", new DateTime(2023, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #95", "OPEN" },
                    { "pr-96", "user-107", new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 8, 1, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #96", "MERGED" },
                    { "pr-97", "user-108", new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #97", "OPEN" },
                    { "pr-98", "user-109", new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc), null, "Feature: Implement feature #98", "OPEN" },
                    { "pr-99", "user-111", new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc), new DateTime(2023, 12, 11, 4, 0, 0, 0, DateTimeKind.Utc), "Feature: Implement feature #99", "MERGED" }
                });

            migrationBuilder.InsertData(
                table: "PullRequestReviewers",
                columns: new[] { "PullRequestId", "ReviewerId" },
                values: new object[,]
                {
                    { "pr-1", "user-1" },
                    { "pr-1", "user-3" },
                    { "pr-10", "user-11" },
                    { "pr-10", "user-13" },
                    { "pr-100", "user-111" },
                    { "pr-100", "user-113" },
                    { "pr-11", "user-11" },
                    { "pr-11", "user-12" },
                    { "pr-12", "user-11" },
                    { "pr-12", "user-12" },
                    { "pr-13", "user-11" },
                    { "pr-13", "user-12" },
                    { "pr-14", "user-11" },
                    { "pr-14", "user-12" },
                    { "pr-15", "user-11" },
                    { "pr-15", "user-12" },
                    { "pr-16", "user-11" },
                    { "pr-16", "user-12" },
                    { "pr-17", "user-11" },
                    { "pr-17", "user-12" },
                    { "pr-18", "user-22" },
                    { "pr-18", "user-23" },
                    { "pr-19", "user-21" },
                    { "pr-19", "user-23" },
                    { "pr-2", "user-1" },
                    { "pr-2", "user-2" },
                    { "pr-20", "user-21" },
                    { "pr-20", "user-22" },
                    { "pr-21", "user-21" },
                    { "pr-21", "user-22" },
                    { "pr-22", "user-21" },
                    { "pr-22", "user-22" },
                    { "pr-23", "user-21" },
                    { "pr-23", "user-22" },
                    { "pr-24", "user-21" },
                    { "pr-24", "user-22" },
                    { "pr-25", "user-21" },
                    { "pr-25", "user-22" },
                    { "pr-26", "user-21" },
                    { "pr-26", "user-22" },
                    { "pr-27", "user-32" },
                    { "pr-27", "user-33" },
                    { "pr-28", "user-31" },
                    { "pr-28", "user-33" },
                    { "pr-29", "user-31" },
                    { "pr-29", "user-32" },
                    { "pr-3", "user-1" },
                    { "pr-3", "user-2" },
                    { "pr-30", "user-31" },
                    { "pr-30", "user-32" },
                    { "pr-31", "user-31" },
                    { "pr-31", "user-32" },
                    { "pr-32", "user-31" },
                    { "pr-32", "user-32" },
                    { "pr-33", "user-31" },
                    { "pr-33", "user-32" },
                    { "pr-34", "user-31" },
                    { "pr-34", "user-32" },
                    { "pr-35", "user-31" },
                    { "pr-35", "user-32" },
                    { "pr-36", "user-42" },
                    { "pr-36", "user-43" },
                    { "pr-37", "user-41" },
                    { "pr-37", "user-43" },
                    { "pr-38", "user-41" },
                    { "pr-38", "user-42" },
                    { "pr-39", "user-41" },
                    { "pr-39", "user-42" },
                    { "pr-4", "user-1" },
                    { "pr-4", "user-2" },
                    { "pr-40", "user-41" },
                    { "pr-40", "user-42" },
                    { "pr-41", "user-41" },
                    { "pr-41", "user-42" },
                    { "pr-42", "user-41" },
                    { "pr-42", "user-42" },
                    { "pr-43", "user-41" },
                    { "pr-43", "user-42" },
                    { "pr-44", "user-41" },
                    { "pr-44", "user-42" },
                    { "pr-45", "user-52" },
                    { "pr-45", "user-53" },
                    { "pr-46", "user-51" },
                    { "pr-46", "user-53" },
                    { "pr-47", "user-51" },
                    { "pr-47", "user-52" },
                    { "pr-48", "user-51" },
                    { "pr-48", "user-52" },
                    { "pr-49", "user-51" },
                    { "pr-49", "user-52" },
                    { "pr-5", "user-1" },
                    { "pr-5", "user-2" },
                    { "pr-50", "user-51" },
                    { "pr-50", "user-52" },
                    { "pr-51", "user-51" },
                    { "pr-51", "user-52" },
                    { "pr-52", "user-51" },
                    { "pr-52", "user-52" },
                    { "pr-53", "user-51" },
                    { "pr-53", "user-52" },
                    { "pr-54", "user-62" },
                    { "pr-54", "user-63" },
                    { "pr-55", "user-61" },
                    { "pr-55", "user-63" },
                    { "pr-56", "user-61" },
                    { "pr-56", "user-62" },
                    { "pr-57", "user-61" },
                    { "pr-57", "user-62" },
                    { "pr-58", "user-61" },
                    { "pr-58", "user-62" },
                    { "pr-59", "user-61" },
                    { "pr-59", "user-62" },
                    { "pr-6", "user-1" },
                    { "pr-6", "user-2" },
                    { "pr-60", "user-61" },
                    { "pr-60", "user-62" },
                    { "pr-61", "user-61" },
                    { "pr-61", "user-62" },
                    { "pr-62", "user-61" },
                    { "pr-62", "user-62" },
                    { "pr-63", "user-72" },
                    { "pr-63", "user-73" },
                    { "pr-64", "user-71" },
                    { "pr-64", "user-73" },
                    { "pr-65", "user-71" },
                    { "pr-65", "user-72" },
                    { "pr-66", "user-71" },
                    { "pr-66", "user-72" },
                    { "pr-67", "user-71" },
                    { "pr-67", "user-72" },
                    { "pr-68", "user-71" },
                    { "pr-68", "user-72" },
                    { "pr-69", "user-71" },
                    { "pr-69", "user-72" },
                    { "pr-7", "user-1" },
                    { "pr-7", "user-2" },
                    { "pr-70", "user-71" },
                    { "pr-70", "user-72" },
                    { "pr-71", "user-71" },
                    { "pr-71", "user-72" },
                    { "pr-72", "user-82" },
                    { "pr-72", "user-83" },
                    { "pr-73", "user-81" },
                    { "pr-73", "user-83" },
                    { "pr-74", "user-81" },
                    { "pr-74", "user-82" },
                    { "pr-75", "user-81" },
                    { "pr-75", "user-82" },
                    { "pr-76", "user-81" },
                    { "pr-76", "user-82" },
                    { "pr-77", "user-81" },
                    { "pr-77", "user-82" },
                    { "pr-78", "user-81" },
                    { "pr-78", "user-82" },
                    { "pr-79", "user-81" },
                    { "pr-79", "user-82" },
                    { "pr-8", "user-1" },
                    { "pr-8", "user-2" },
                    { "pr-80", "user-81" },
                    { "pr-80", "user-82" },
                    { "pr-81", "user-92" },
                    { "pr-81", "user-93" },
                    { "pr-82", "user-91" },
                    { "pr-82", "user-93" },
                    { "pr-83", "user-91" },
                    { "pr-83", "user-92" },
                    { "pr-84", "user-91" },
                    { "pr-84", "user-92" },
                    { "pr-85", "user-91" },
                    { "pr-85", "user-92" },
                    { "pr-86", "user-91" },
                    { "pr-86", "user-92" },
                    { "pr-87", "user-91" },
                    { "pr-87", "user-92" },
                    { "pr-88", "user-91" },
                    { "pr-88", "user-92" },
                    { "pr-89", "user-91" },
                    { "pr-89", "user-92" },
                    { "pr-9", "user-12" },
                    { "pr-9", "user-13" },
                    { "pr-90", "user-102" },
                    { "pr-90", "user-103" },
                    { "pr-91", "user-101" },
                    { "pr-91", "user-103" },
                    { "pr-92", "user-101" },
                    { "pr-92", "user-102" },
                    { "pr-93", "user-101" },
                    { "pr-93", "user-102" },
                    { "pr-94", "user-101" },
                    { "pr-94", "user-102" },
                    { "pr-95", "user-101" },
                    { "pr-95", "user-102" },
                    { "pr-96", "user-101" },
                    { "pr-96", "user-102" },
                    { "pr-97", "user-101" },
                    { "pr-97", "user-102" },
                    { "pr-98", "user-101" },
                    { "pr-98", "user-102" },
                    { "pr-99", "user-112" },
                    { "pr-99", "user-113" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_PullRequestReviewers_ReviewerId",
                table: "PullRequestReviewers",
                column: "ReviewerId");

            migrationBuilder.CreateIndex(
                name: "IX_PullRequests_AuthorId",
                table: "PullRequests",
                column: "AuthorId");

            migrationBuilder.CreateIndex(
                name: "IX_Users_TeamName",
                table: "Users",
                column: "TeamName");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PullRequestReviewers");

            migrationBuilder.DropTable(
                name: "PullRequests");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "Teams");
        }
    }
}
